// Generated by Debugger/tools/generate_protocol.py. Do not edit by hand.
#pragma once

#include "common/types.hpp"

namespace Lua::Debugger::Remote {

inline constexpr u32 kProtocolMagic = 0x594C4431U;
inline constexpr u16 kProtocolVersionMajor = 1U;
inline constexpr u16 kProtocolVersionMinor = 0U;
inline constexpr usize kProtocolHeaderSize = 28U;
inline constexpr usize kProtocolMaxFrameBytes = 1048576U;
inline constexpr usize kProtocolMaxStringBytes = 65536U;
inline constexpr usize kProtocolMaxCollectionItems = 4096U;
inline constexpr u32 kProtocolHandshakeTimeoutMs = 5000U;
inline constexpr u32 kProtocolRequestTimeoutMs = 10000U;
inline constexpr u32 kProtocolHeartbeatIntervalMs = 5000U;
inline constexpr u32 kProtocolIdleTimeoutMs = 30000U;
inline constexpr const char* kProtocolSchemaSha256 = "e9f558515fc1b2ac25fa77379c662b242d2697433d0fd9e43d5365ca9226df9f";

enum class ProtocolMessageKind : u8 {
    Hello = 1,
    HelloAck = 2,
    Request = 3,
    Response = 4,
    Event = 5,
    Ping = 6,
    Pong = 7,
    Goodbye = 8,
};
enum class ProtocolCommand : u16 {
    None = 0,
    SetBreakpoints = 1,
    Pause = 2,
    Continue = 3,
    Next = 4,
    StepIn = 5,
    StepOut = 6,
    Threads = 7,
    StackTrace = 8,
    Scopes = 9,
    Variables = 10,
    Evaluate = 11,
    SetExceptionBreakpoints = 12,
    ExceptionInfo = 13,
    Detach = 14,
    States = 15,
    SelectState = 16,
};
enum class ProtocolEvent : u16 {
    None = 0,
    Stopped = 1,
    Continued = 2,
    Output = 3,
    BreakpointChanged = 4,
    ThreadStarted = 5,
    ThreadExited = 6,
    Terminated = 7,
    StateStarted = 8,
    StateExited = 9,
};
enum class ProtocolStatus : u16 {
    Okay = 0,
    InvalidArgument = 1,
    InvalidState = 2,
    StaleReference = 3,
    NotFound = 4,
    NotSupported = 5,
    ResourceLimit = 6,
    Terminated = 7,
    ProtocolError = 8,
    InternalError = 9,
    Unauthorized = 10,
    VersionMismatch = 11,
    Timeout = 12,
    Busy = 13,
};
enum class ProtocolCapability : u64 {
    Breakpoints = 1ULL << 0U,
    PauseContinue = 1ULL << 1U,
    Stepping = 1ULL << 2U,
    Stack = 1ULL << 3U,
    Variables = 1ULL << 4U,
    EvaluateReadOnly = 1ULL << 5U,
    ExceptionInfo = 1ULL << 6U,
    MultipleStates = 1ULL << 7U,
    CoroutineThreads = 1ULL << 8U,
    SourcePathMapping = 1ULL << 9U,
    Reconnect = 1ULL << 10U,
    GlobalPauseOnly = 1ULL << 11U,
};

constexpr u64 capabilityBit(ProtocolCapability capability) noexcept {
    return static_cast<u64>(capability);
}

} // namespace Lua::Debugger::Remote
